import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Pie from '@/components/PieChart'
import Button from '@/components/Button'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Pie/>
        <div>

        </div>
        <button className={styles.button}><Link href="" className={styles.link}>Yes</Link></button>
        <Link href="" className={styles.link}><button className={styles.button}>Yes</button></Link>
      </main>
    </>
  )
}
