const substanceAbuseKeywords = [
  "more",
  "addiction",
  "substance abuse",
  "substance misuse",
  "misuse",
  "drug",
  "drugs",
  "weed",
  "alcoholism",
  "alcoholic",
  "alcohol",
  "rehab",
  "treatment",
  "withdrawal",
  "heroin",
  "dependence",
  "opioid",
  "heroin",
  "meth",
  "cocaine",
  "prescription",
  "narcotic",
  "dope",
  "pot",
  "crack",
  "crystal",
  "speed",
  "smack",
  "booze",
  "reefer",
  "blunt",
  "joint",
  "detox",
  "therapy",
  "counseling",
  "overdose",
  "intoxication",
  "craving",
  "relapse",
  "support group",
  "12-step program",
  "AA",
  "NA",
  "inpatient",
  "outpatient",
  "binge",
  "sobriety",
  "sober living",
  "harm reduction",
  "abstinence",
  "recovery",
  "dual diagnosis",
  "intervention",
  "codependency",
  "enabling",
  "addictive behavior",
  "tolerance",
  "substance use disorder",
  "psychoactive",
  "amphetamine",
  "benzodiazepine",
  "barbiturate",
  "hallucinogen",
  "marijuana",
  "cannabis",
  "LSD",
  "MDMA",
  "ecstasy",
  "inhalant",
  "stimulant",
  "depressant",
  "anabolic steroid",
  "nicotine",
  "tobacco",
  "vaping",
  "e-cigarette",
  "alcoholics anonymous",
  "narcotics anonymous",
  "alcohol use disorder",
  "drug abuse",
  "drug addiction",
  "drug dependence",
  "drug use",
  "drug use disorder",
  "opioid use disorder",
  "opioid addiction",
  "opioid dependence",
  "opioid abuse",
  "opioid misuse",
  "opioid epidemic",
  "opioid crisis",
  "opioid overdose",
  "opioid withdrawal",
  "opioid treatment",
  "opioid rehab",
  "opioid detox",
  "opioid therapy",
  "opioid counseling",
  "heroin use disorder",
  "heroin addiction",
  "heroin dependence",
  "heroin abuse",
  "heroin misuse",
  "heroin epidemic",
  "heroin crisis",
  "heroin overdose",
  "heroin withdrawal",
  "heroin treatment",
  "heroin rehab",
  "heroin detox",
  "heroin therapy",
  "heroin counseling",
  "meth use disorder",
  "meth addiction",
  "meth dependence",
  "meth abuse",
  "meth misuse",
  "meth epidemic",
  "meth crisis",
  "meth overdose",
  "meth withdrawal",
  "meth treatment",
  "meth rehab",
  "meth detox",
  "methamphetamine use disorder",
  "methamphetamine addiction",
  "methamphetamine dependence",
  "methamphetamine abuse",
  "methamphetamine misuse",
  "methamphetamine epidemic",
  "methamphetamine crisis",
  "methamphetamine overdose",
  "methamphetamine withdrawal",
  "methamphetamine treatment",
  "methamphetamine rehab",
  "methamphetamine detox",
  "methamphetamine therapy",
  "methamphetamine counseling",
  "cocaine use disorder",
  "cocaine addiction",
  "cocaine dependence",
  "cocaine abuse",
  "cocaine misuse",
  "cocaine epidemic",
  "cocaine crisis",
  "cocaine overdose",
  "cocaine withdrawal",
  "cocaine treatment",
  "cocaine rehab",
  "cocaine detox",
  "cocaine therapy",
  "cocaine counseling",
  "prescription drug use disorder",
  "prescription drug addiction",
  "prescription drug dependence",
  "prescription drug abuse",
  "prescription drug misuse",
  "prescription drug epidemic",
  "prescription drug crisis",
  "prescription drug overdose",
  "prescription drug withdrawal",
  "prescription drug treatment",
  "prescription drug rehab",
  "prescription drug detox",
  "prescription drug therapy",
  "prescription drug counseling",
  "benzodiazepine use disorder",
  "benzodiazepine addiction",
  "benzodiazepine dependence",
  "benzodiazepine abuse",
  "benzodiazepine misuse",
  "benzodiazepine epidemic",
  "benzodiazepine crisis",
  "benzodiazepine overdose",
  "benzodiazepine withdrawal",
  "benzodiazepine treatment",
  "benzodiazepine rehab",
  "benzodiazepine detox",
  "benzodiazepine therapy",
  "benzodiazepine counseling",
  "barbiturate use disorder",
  "barbiturate addiction",
  "barbiturate dependence",
  "barbiturate abuse",
  "barbiturate misuse",
  "barbiturate epidemic",
  "barbiturate crisis",
  "barbiturate overdose",
  "barbiturate withdrawal",
  "barbiturate treatment",
  "barbiturate rehab",
  "barbiturate detox",
  "barbiturate therapy",
  "barbiturate counseling",
  "hallucinogen use disorder",
  "hallucinogen addiction",
  "hallucinogen dependence",
  "hallucinogen abuse",
  "hallucinogen misuse",
  "hallucinogen epidemic",
  "hallucinogen crisis",
  "hallucinogen overdose",
  "hallucinogen withdrawal",
  "hallucinogen treatment",
  "hallucinogen rehab",
  "hallucinogen detox",
  "hallucinogen therapy",
  "hallucinogen counseling",
  "marijuana use disorder",
  "marijuana addiction",
  "marijuana dependence",
  "marijuana abuse",
  "marijuana misuse",
  "marijuana epidemic",
  "marijuana crisis",
  "marijuana overdose",
  "marijuana withdrawal",
  "marijuana treatment",
  "marijuana rehab",
  "marijuana detox",

  "marijuana therapy",
  "marijuana counseling",
  "cannabis use disorder",
  "cannabis addiction",
  "cannabis dependence",
  "cannabis abuse",
  "cannabis misuse",
  "cannabis epidemic",
  "cannabis crisis",
  "cannabis overdose",
  "cannabis withdrawal",
  "cannabis treatment",
  "cannabis rehab",
  "cannabis detox",
  "cannabis therapy",
  "cannabis counseling",
  "LSD use disorder",
  "LSD addiction",
  "LSD dependence",

  "LSD abuse",
  "LSD misuse",
  "LSD epidemic",
  "LSD crisis",
  "LSD overdose",
  "LSD withdrawal",
  "LSD treatment",
  "LSD rehab",
  "LSD detox",
  "LSD therapy",
  "LSD counseling",
  "MDMA use disorder",
  "MDMA addiction",
  "MDMA dependence",
  "MDMA abuse",
  "MDMA misuse",
  "MDMA epidemic",
  "MDMA crisis",
  "MDMA overdose",
  "MDMA withdrawal",
  "MDMA treatment",
  "MDMA rehab",
  "MDMA detox",
  "MDMA therapy",
  "MDMA counseling",
];

export function isSubstanceAbuseRelated(message) {
  const lowerCaseMessage = message.toLowerCase();
  return substanceAbuseKeywords.some((keyword) =>
    lowerCaseMessage.includes(keyword)
  );
}
